#!/bin/bash

cd "${0%/*}"


REPONAMES=("containds-all-basic" "containds-all-scipy")
BASEREPONAMES=("ideonate\/jh-voila-oauth-singleuser" "ideonate\/jh-voila-oauth-scipy")

for index in {0..1}
do
    reponame=${REPONAMES[index]}
    echo "Replicating skeleton to $reponame"

    cd "$reponame"
    pwd

    cp -r ../skeleton/* .

    stacks_sed_reponame=${BASEREPONAMES[index]}

    echo $stacks_sed_reponame

    sed -i '' -e "s/{{TEMPLATE_BASE_REPO}}/$stacks_sed_reponame/g" Dockerfile

    cd ..
    echo
done
